import Navbar from "@/components/Navbar";
import "./globals.css";
import "./pages.css";

export const metadata = {
  title: "New title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[color:var(--background-color)]">
        <Navbar></Navbar>
        <div className="pl-10 pt-10">{children}</div>
      </body>
    </html>
  );
}
