import Navbar from "@/components/Navbar";
import "./globals.css";
import "./pages.css";
import { Providers } from "./providers";

export const metadata = {
  title: "New title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className="bg-[color:var(--background-color)]">
      <Providers>
          <Navbar></Navbar>
          <div className="pl-10 pt-10">{children}</div>
      </Providers>
        </body>
    </html>
  );
}
